/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import static Interface.VisitorRegisterPage.ic_no;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author jianlin070
 */
public class VisitorCheckStatusPage extends javax.swing.JFrame {
    
    public static String ic_no;
    
    /**
     * Creates new form LandingForm
     * @param ic
     */
    public VisitorCheckStatusPage(String ic) {
        initComponents();
        ic_no = ic;
    }
    
    //validation for status
    public boolean validateStatus(){
        String tic_no = txt_tic_no.getText();

        
        if (tic_no.equals("") ){
            JOptionPane.showMessageDialog(this, "Please enter Ticket Number");
            return false;
        }
        
        //26 digits
        if (tic_no.length() != 26){
            JOptionPane.showMessageDialog(this, "Please enter valid Ticket Number");
            return false;
        }
    
        return true;    
    }
    
    //check status
    public void checkSatus(){
        
        btn_resubmit.setVisible(false);
        
        String tic_no = txt_tic_no.getText();
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "select status,declined_reason from request where tic_no = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, tic_no);
          
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                if(rs.getInt("status") == 0){
                    lbl_status.setText("Pending");
                    lbl_status.setForeground(Color.yellow);
                }
                
                if(rs.getInt("status") == 1){
                    lbl_status.setText("Approved");
                    lbl_status.setForeground(Color.green);
                }
                
                if(rs.getInt("status") == 2){
                    lbl_status.setText("Declined");
                    lbl_status.setForeground(Color.red);
                    lbl_reason.setText("Reason:");
                    lbl_reason1.setText(rs.getString("declined_reason"));
                    btn_resubmit.setVisible(true);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Incorrect ticket number");
            }
            
        } catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSCalendarBeanInfo1 = new rojeru_san.componentes.RSCalendarBeanInfo();
        rSCalendarBeanInfo2 = new rojeru_san.componentes.RSCalendarBeanInfo();
        testUtils1 = new com.mysql.cj.util.TestUtils();
        rSDateChooserBeanInfo1 = new rojeru_san.componentes.RSDateChooserBeanInfo();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_homepage = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_reason1 = new javax.swing.JLabel();
        txt_tic_no = new app.bolivia.swing.JCTextField();
        jLabel3 = new javax.swing.JLabel();
        lbl_reason = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        btn_resubmit = new javax.swing.JButton();
        btn_check = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(950, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bangla Sangam MN", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Check Status");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(382, 25));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 320, 60));

        btn_homepage.setBackground(new java.awt.Color(153, 153, 153));
        btn_homepage.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btn_homepage.setForeground(new java.awt.Color(255, 255, 255));
        btn_homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/visitor-register-homepage.png"))); // NOI18N
        btn_homepage.setText("Homepage");
        btn_homepage.setToolTipText("");
        btn_homepage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_homepage.setOpaque(true);
        btn_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homepageMouseClicked(evt);
            }
        });
        btn_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homepageActionPerformed(evt);
            }
        });
        jPanel1.add(btn_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 90));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(2000, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_reason1.setFont(new java.awt.Font("Bangla Sangam MN", 0, 36)); // NOI18N
        lbl_reason1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reason1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_reason1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_reason1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_reason1.setPreferredSize(new java.awt.Dimension(382, 25));
        jPanel2.add(lbl_reason1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 480, 150));

        txt_tic_no.setBackground(new java.awt.Color(102, 153, 255));
        txt_tic_no.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_tic_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tic_no.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txt_tic_no.setPlaceholder("                         Enter Ticket Number:");
        txt_tic_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tic_noFocusLost(evt);
            }
        });
        txt_tic_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tic_noActionPerformed(evt);
            }
        });
        jPanel2.add(txt_tic_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 590, 50));

        jLabel3.setFont(new java.awt.Font("Bangla Sangam MN", 0, 44)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please enter your Ticket Number:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(382, 25));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 640, 60));

        lbl_reason.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        lbl_reason.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reason.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_reason.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_reason.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_reason.setPreferredSize(new java.awt.Dimension(382, 25));
        jPanel2.add(lbl_reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 150, 60));

        jLabel5.setFont(new java.awt.Font("Bangla Sangam MN", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Status:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setPreferredSize(new java.awt.Dimension(382, 25));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 150, 60));

        lbl_status.setFont(new java.awt.Font("Bangla Sangam MN", 0, 36)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(255, 255, 255));
        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_status.setText("-");
        lbl_status.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_status.setPreferredSize(new java.awt.Dimension(382, 25));
        jPanel2.add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 300, 60));

        btn_resubmit.setBackground(new java.awt.Color(153, 153, 153));
        btn_resubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        btn_resubmit.setForeground(new java.awt.Color(255, 255, 255));
        btn_resubmit.setText("Resumit");
        btn_resubmit.setToolTipText("");
        btn_resubmit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_resubmit.setOpaque(true);
        btn_resubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resubmitMouseClicked(evt);
            }
        });
        btn_resubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_resubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 140, 70));
        btn_resubmit.setVisible(false);

        btn_check.setBackground(new java.awt.Color(153, 153, 153));
        btn_check.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        btn_check.setForeground(new java.awt.Color(255, 255, 255));
        btn_check.setText("Check");
        btn_check.setToolTipText("");
        btn_check.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_check.setOpaque(true);
        btn_check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_checkMouseClicked(evt);
            }
        });
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        jPanel2.add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 260, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tic_noFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tic_noFocusLost

    }//GEN-LAST:event_txt_tic_noFocusLost

    private void txt_tic_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tic_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tic_noActionPerformed

    private void btn_resubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resubmitMouseClicked
        VisitorRegisterPage register = new VisitorRegisterPage(ic_no);
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_resubmitMouseClicked

    private void btn_resubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resubmitActionPerformed

    private void btn_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homepageMouseClicked
        VisitorHomepage home = new VisitorHomepage(ic_no);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homepageMouseClicked

    private void btn_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homepageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homepageActionPerformed

    private void btn_checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_checkMouseClicked
       if (validateStatus()){
            checkSatus();
        }
    }//GEN-LAST:event_btn_checkMouseClicked

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitorCheckStatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitorCheckStatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitorCheckStatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitorCheckStatusPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitorCheckStatusPage(ic_no).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_check;
    private javax.swing.JButton btn_homepage;
    private javax.swing.JButton btn_resubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_reason;
    private javax.swing.JLabel lbl_reason1;
    private javax.swing.JLabel lbl_status;
    private rojeru_san.componentes.RSCalendarBeanInfo rSCalendarBeanInfo1;
    private rojeru_san.componentes.RSCalendarBeanInfo rSCalendarBeanInfo2;
    private rojeru_san.componentes.RSDateChooserBeanInfo rSDateChooserBeanInfo1;
    private com.mysql.cj.util.TestUtils testUtils1;
    private app.bolivia.swing.JCTextField txt_tic_no;
    // End of variables declaration//GEN-END:variables
}
